import type { Shift } from "./types";

/** Fallback when the API is empty or unreachable during local demos. */
export const MOCK_SHIFTS: Shift[] = [
  {
    id: "mock-1",
    clientProfileId: null,
    requiredQualification: "CNA",
    date: "2026-07-21",
    startTime: "08:00:00",
    endTime: "16:00:00",
    addressLine: "120 Beacon St",
    city: "Boston",
    state: "MA",
    zip: "02116",
    lat: 42.355,
    lng: -71.072,
    payRate: 22,
    billRate: 34,
    status: "OPEN",
    scheduleType: "ONE_OFF",
    seriesId: null,
    notes: "Mobility assistance, medication reminders.",
    platformPaid: false,
    createdBy: "mock",
    createdAt: "2026-07-18T12:00:00Z",
  },
  {
    id: "mock-2",
    clientProfileId: null,
    requiredQualification: "HHA",
    date: "2026-07-22",
    startTime: "09:00:00",
    endTime: "17:00:00",
    addressLine: "45 Elm St",
    city: "Worcester",
    state: "MA",
    zip: "01609",
    lat: 42.262,
    lng: -71.802,
    payRate: 20,
    billRate: 30,
    status: "OPEN",
    scheduleType: "ONE_OFF",
    seriesId: null,
    notes: "Group setting, meal prep assistance.",
    platformPaid: false,
    createdBy: "mock",
    createdAt: "2026-07-18T12:00:00Z",
  },
  {
    id: "mock-3",
    clientProfileId: null,
    requiredQualification: "PCA",
    date: "2026-07-23",
    startTime: "18:00:00",
    endTime: "22:00:00",
    addressLine: "78 Main St",
    city: "Cambridge",
    state: "MA",
    zip: "02139",
    lat: 42.373,
    lng: -71.109,
    payRate: 21,
    billRate: 32,
    status: "OPEN",
    scheduleType: "ONE_OFF",
    seriesId: null,
    notes: null,
    platformPaid: false,
    createdBy: "mock",
    createdAt: "2026-07-18T12:00:00Z",
  },
  {
    id: "mock-4",
    clientProfileId: null,
    requiredQualification: "LPN",
    date: "2026-07-19",
    startTime: "07:00:00",
    endTime: "15:00:00",
    addressLine: "9 Harbor Ave",
    city: "Quincy",
    state: "MA",
    zip: "02169",
    lat: 42.252,
    lng: -71.002,
    payRate: 32,
    billRate: 48,
    status: "CONFIRMED",
    scheduleType: "ONE_OFF",
    seriesId: null,
    notes: "Wound care, skilled nursing visit.",
    platformPaid: false,
    createdBy: "mock",
    createdAt: "2026-07-18T12:00:00Z",
  },
];
